// <auto-generated />
using System;
using Agenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenda.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    partial class AgendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdioma")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAgenda")
                        .HasColumnType("int");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoTrasladoSiguienteOficinaMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdioma");

                    b.HasIndex("IdAgenda");

                    b.HasIndex("IdParticipante");

                    b.ToTable("AgendaDetalle", (string)null);
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadReunionesMeta")
                        .HasColumnType("int");

                    b.Property<int>("DuracionReunionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInversor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdInversor");

                    b.ToTable("Agenda", (string)null);
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAgenda")
                        .HasColumnType("int");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdParticipante");

                    b.HasIndex("IdAgenda", "IdParticipante")
                        .IsUnique();

                    b.ToTable("AgendaParticipante", (string)null);
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Idioma", b =>
                {
                    b.Property<string>("CodigoIdioma")
                        .HasColumnType("char(2)");

                    b.Property<string>("IdiomaNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Idioma");

                    b.HasKey("CodigoIdioma");

                    b.ToTable("Idioma", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoIdioma = "ES",
                            IdiomaNombre = "Español"
                        },
                        new
                        {
                            CodigoIdioma = "EN",
                            IdiomaNombre = "Inglés"
                        },
                        new
                        {
                            CodigoIdioma = "FR",
                            IdiomaNombre = "Francés"
                        },
                        new
                        {
                            CodigoIdioma = "PT",
                            IdiomaNombre = "Portugués"
                        },
                        new
                        {
                            CodigoIdioma = "DE",
                            IdiomaNombre = "Alemán"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Inversor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpresaRepresenta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaFinVisita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioVisita")
                        .HasColumnType("datetime2");

                    b.Property<string>("LugarHospedaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Inversor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpresaRepresenta = "GreenTech Capital",
                            FechaFinVisita = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioVisita = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarHospedaje = "Hotel Real InterContinental, Escazú",
                            NombreCompleto = "John Anderson",
                            PaisOrigen = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            EmpresaRepresenta = "Bavaria Manufacturing Group",
                            FechaFinVisita = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioVisita = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LugarHospedaje = "AC Hotel San José Escazú",
                            NombreCompleto = "Maria Schmidt",
                            PaisOrigen = "Alemania"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.InversorIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdioma")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<int>("IdInversor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdioma");

                    b.HasIndex("IdInversor", "CodigoIdioma")
                        .IsUnique();

                    b.ToTable("InversorIdioma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIdioma = "EN",
                            IdInversor = 1
                        },
                        new
                        {
                            Id = 2,
                            CodigoIdioma = "ES",
                            IdInversor = 1
                        },
                        new
                        {
                            Id = 3,
                            CodigoIdioma = "DE",
                            IdInversor = 2
                        },
                        new
                        {
                            Id = 4,
                            CodigoIdioma = "EN",
                            IdInversor = 2
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.MatrizTraslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOficinaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdOficinaOrigen")
                        .HasColumnType("int");

                    b.Property<int>("TiempoMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOficinaDestino");

                    b.HasIndex("IdOficinaOrigen", "IdOficinaDestino")
                        .IsUnique();

                    b.ToTable("MatrizTraslado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdOficinaDestino = 2,
                            IdOficinaOrigen = 1,
                            TiempoMinutos = 25
                        },
                        new
                        {
                            Id = 2,
                            IdOficinaDestino = 3,
                            IdOficinaOrigen = 1,
                            TiempoMinutos = 55
                        },
                        new
                        {
                            Id = 3,
                            IdOficinaDestino = 4,
                            IdOficinaOrigen = 1,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 4,
                            IdOficinaDestino = 5,
                            IdOficinaOrigen = 1,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 5,
                            IdOficinaDestino = 6,
                            IdOficinaOrigen = 1,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 6,
                            IdOficinaDestino = 1,
                            IdOficinaOrigen = 2,
                            TiempoMinutos = 25
                        },
                        new
                        {
                            Id = 7,
                            IdOficinaDestino = 3,
                            IdOficinaOrigen = 2,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 8,
                            IdOficinaDestino = 4,
                            IdOficinaOrigen = 2,
                            TiempoMinutos = 20
                        },
                        new
                        {
                            Id = 9,
                            IdOficinaDestino = 5,
                            IdOficinaOrigen = 2,
                            TiempoMinutos = 60
                        },
                        new
                        {
                            Id = 10,
                            IdOficinaDestino = 6,
                            IdOficinaOrigen = 2,
                            TiempoMinutos = 40
                        },
                        new
                        {
                            Id = 11,
                            IdOficinaDestino = 1,
                            IdOficinaOrigen = 3,
                            TiempoMinutos = 55
                        },
                        new
                        {
                            Id = 12,
                            IdOficinaDestino = 2,
                            IdOficinaOrigen = 3,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 13,
                            IdOficinaDestino = 4,
                            IdOficinaOrigen = 3,
                            TiempoMinutos = 40
                        },
                        new
                        {
                            Id = 14,
                            IdOficinaDestino = 5,
                            IdOficinaOrigen = 3,
                            TiempoMinutos = 80
                        },
                        new
                        {
                            Id = 15,
                            IdOficinaDestino = 6,
                            IdOficinaOrigen = 3,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 16,
                            IdOficinaDestino = 1,
                            IdOficinaOrigen = 4,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 17,
                            IdOficinaDestino = 2,
                            IdOficinaOrigen = 4,
                            TiempoMinutos = 20
                        },
                        new
                        {
                            Id = 18,
                            IdOficinaDestino = 3,
                            IdOficinaOrigen = 4,
                            TiempoMinutos = 40
                        },
                        new
                        {
                            Id = 19,
                            IdOficinaDestino = 5,
                            IdOficinaOrigen = 4,
                            TiempoMinutos = 70
                        },
                        new
                        {
                            Id = 20,
                            IdOficinaDestino = 6,
                            IdOficinaOrigen = 4,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 21,
                            IdOficinaDestino = 1,
                            IdOficinaOrigen = 5,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 22,
                            IdOficinaDestino = 2,
                            IdOficinaOrigen = 5,
                            TiempoMinutos = 60
                        },
                        new
                        {
                            Id = 23,
                            IdOficinaDestino = 3,
                            IdOficinaOrigen = 5,
                            TiempoMinutos = 80
                        },
                        new
                        {
                            Id = 24,
                            IdOficinaDestino = 4,
                            IdOficinaOrigen = 5,
                            TiempoMinutos = 70
                        },
                        new
                        {
                            Id = 25,
                            IdOficinaDestino = 6,
                            IdOficinaOrigen = 5,
                            TiempoMinutos = 55
                        },
                        new
                        {
                            Id = 26,
                            IdOficinaDestino = 1,
                            IdOficinaOrigen = 6,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 27,
                            IdOficinaDestino = 2,
                            IdOficinaOrigen = 6,
                            TiempoMinutos = 40
                        },
                        new
                        {
                            Id = 28,
                            IdOficinaDestino = 3,
                            IdOficinaOrigen = 6,
                            TiempoMinutos = 35
                        },
                        new
                        {
                            Id = 29,
                            IdOficinaDestino = 4,
                            IdOficinaOrigen = 6,
                            TiempoMinutos = 45
                        },
                        new
                        {
                            Id = 30,
                            IdOficinaDestino = 5,
                            IdOficinaOrigen = 6,
                            TiempoMinutos = 55
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Oficina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Oficina", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "San José, Costa Rica",
                            Latitud = 9.928100m,
                            Longitud = -84.090700m,
                            Nombre = "CINDE San José"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Escazú, San José, Costa Rica",
                            Latitud = 9.918900m,
                            Longitud = -84.139900m,
                            Nombre = "PROCOMER Escazú"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Coyol, Alajuela, Costa Rica",
                            Latitud = 9.996900m,
                            Longitud = -84.257300m,
                            Nombre = "Zona Franca Coyol"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Santa Ana, San José, Costa Rica",
                            Latitud = 9.932400m,
                            Longitud = -84.182600m,
                            Nombre = "Parque Empresarial Forum"
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "La Lima, Cartago, Costa Rica",
                            Latitud = 9.868600m,
                            Longitud = -83.940000m,
                            Nombre = "Zona Franca La Lima"
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Heredia Centro, Costa Rica",
                            Latitud = 9.998100m,
                            Longitud = -84.116500m,
                            Nombre = "Oficina Municipal de Heredia"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdOficina")
                        .HasColumnType("int");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdOficina");

                    b.ToTable("Participante", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Director de Atracción de Inversión",
                            Estado = true,
                            IdOficina = 1,
                            Institucion = "CINDE",
                            NombreCompleto = "Carlos Rodríguez Mora"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Gerente de Exportaciones",
                            Estado = true,
                            IdOficina = 2,
                            Institucion = "PROCOMER",
                            NombreCompleto = "María Fernanda Vargas"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Gerente de Operaciones",
                            Estado = true,
                            IdOficina = 3,
                            Institucion = "Zona Franca Coyol",
                            NombreCompleto = "José Pablo Herrera"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "Directora Comercial",
                            Estado = true,
                            IdOficina = 4,
                            Institucion = "Parque Empresarial Forum",
                            NombreCompleto = "Laura Jiménez Solís"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "Coordinador de Inversión",
                            Estado = true,
                            IdOficina = 5,
                            Institucion = "Zona Franca La Lima",
                            NombreCompleto = "Andrés Quesada Brenes"
                        },
                        new
                        {
                            Id = 6,
                            Cargo = "Alcaldía de Desarrollo Económico",
                            Estado = true,
                            IdOficina = 6,
                            Institucion = "Municipalidad de Heredia",
                            NombreCompleto = "Sofía Castro Rojas"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.ParticipanteHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdParticipante");

                    b.ToTable("ParticipanteHorario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaHoraFin = new DateTime(2026, 7, 6, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaHoraFin = new DateTime(2026, 7, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 2
                        },
                        new
                        {
                            Id = 3,
                            FechaHoraFin = new DateTime(2026, 7, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 3
                        },
                        new
                        {
                            Id = 4,
                            FechaHoraFin = new DateTime(2026, 7, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 4
                        },
                        new
                        {
                            Id = 5,
                            FechaHoraFin = new DateTime(2026, 7, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 5
                        },
                        new
                        {
                            Id = 6,
                            FechaHoraFin = new DateTime(2026, 7, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraInicio = new DateTime(2026, 7, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IdParticipante = 6
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.ParticipanteIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdioma")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdioma");

                    b.HasIndex("IdParticipante", "CodigoIdioma")
                        .IsUnique();

                    b.ToTable("ParticipanteIdioma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIdioma = "ES",
                            IdParticipante = 1
                        },
                        new
                        {
                            Id = 2,
                            CodigoIdioma = "EN",
                            IdParticipante = 1
                        },
                        new
                        {
                            Id = 3,
                            CodigoIdioma = "ES",
                            IdParticipante = 2
                        },
                        new
                        {
                            Id = 4,
                            CodigoIdioma = "EN",
                            IdParticipante = 2
                        },
                        new
                        {
                            Id = 5,
                            CodigoIdioma = "ES",
                            IdParticipante = 3
                        },
                        new
                        {
                            Id = 6,
                            CodigoIdioma = "EN",
                            IdParticipante = 3
                        },
                        new
                        {
                            Id = 7,
                            CodigoIdioma = "FR",
                            IdParticipante = 4
                        },
                        new
                        {
                            Id = 8,
                            CodigoIdioma = "EN",
                            IdParticipante = 4
                        },
                        new
                        {
                            Id = 9,
                            CodigoIdioma = "ES",
                            IdParticipante = 5
                        },
                        new
                        {
                            Id = 10,
                            CodigoIdioma = "EN",
                            IdParticipante = 5
                        },
                        new
                        {
                            Id = 11,
                            CodigoIdioma = "ES",
                            IdParticipante = 6
                        },
                        new
                        {
                            Id = 12,
                            CodigoIdioma = "EN",
                            IdParticipante = 6
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaDetalle", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Idioma", "Idioma")
                        .WithMany()
                        .HasForeignKey("CodigoIdioma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.AgendaEntity", "Agenda")
                        .WithMany("Detalles")
                        .HasForeignKey("IdAgenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.Participante", "Participante")
                        .WithMany("AgendaDetalles")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Idioma");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaEntity", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Inversor", "Inversor")
                        .WithMany("Agendas")
                        .HasForeignKey("IdInversor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inversor");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaParticipante", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.AgendaEntity", "Agenda")
                        .WithMany("Participantes")
                        .HasForeignKey("IdAgenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.Participante", "Participante")
                        .WithMany("AgendaParticipantes")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.InversorIdioma", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Idioma", "Idioma")
                        .WithMany("InversorIdiomas")
                        .HasForeignKey("CodigoIdioma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.Inversor", "Inversor")
                        .WithMany("Idiomas")
                        .HasForeignKey("IdInversor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("Inversor");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.MatrizTraslado", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Oficina", "OficinaDestino")
                        .WithMany()
                        .HasForeignKey("IdOficinaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.Oficina", "OficinaOrigen")
                        .WithMany()
                        .HasForeignKey("IdOficinaOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OficinaDestino");

                    b.Navigation("OficinaOrigen");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Participante", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Participantes")
                        .HasForeignKey("IdOficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.ParticipanteHorario", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Participante", "Participante")
                        .WithMany("Horarios")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.ParticipanteIdioma", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Idioma", "Idioma")
                        .WithMany("ParticipanteIdiomas")
                        .HasForeignKey("CodigoIdioma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.Participante", "Participante")
                        .WithMany("Idiomas")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.AgendaEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Idioma", b =>
                {
                    b.Navigation("InversorIdiomas");

                    b.Navigation("ParticipanteIdiomas");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Inversor", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Idiomas");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Oficina", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Participante", b =>
                {
                    b.Navigation("AgendaDetalles");

                    b.Navigation("AgendaParticipantes");

                    b.Navigation("Horarios");

                    b.Navigation("Idiomas");
                });
#pragma warning restore 612, 618
        }
    }
}
